/* Sample data for the 7fil prototype.
   All copy is in Turkish — sample listings span İstanbul, İzmir, Çeşme,
   Bodrum, Ankara, Bursa.
*/

const fmtTRY = (n) => n.toLocaleString('tr-TR') + ' ₺';

const STEPS = [
  { num: 1, label: 'Ara',         labelFull: 'Ara & Keşfet',          icon: 'IconSearch' },
  { num: 2, label: 'Değerle',     labelFull: 'Atlas AI Değerleme',    icon: 'IconCompass' },
  { num: 3, label: 'Doğrula',     labelFull: 'Hukuki Doğrulama',      icon: 'IconShield' },
  { num: 4, label: 'Finanse Et',  labelFull: 'Mortgage & Finansman',  icon: 'IconCoin' },
  { num: 5, label: 'Sigorta Et',  labelFull: 'Sigorta & DASK',        icon: 'IconKey' },
  { num: 6, label: 'İmzala',      labelFull: 'Avukat Onaylı İmza',    icon: 'IconDocument' },
  { num: 7, label: 'Taşın',       labelFull: 'Taşınma & Mülk Yönetimi', icon: 'IconHome' },
];

const LISTINGS = [
  {
    id: 'l1',
    kind: 'satilik',
    title: 'Moda’da deniz manzaralı 3+1 daire',
    district: 'Moda', city: 'Kadıköy · İstanbul',
    price: 8500000,
    rooms: '3+1',
    area: 145,
    floor: '4',
    age: 6,
    aidat: 1200,
    heat: 'Doğalgaz',
    scene: 'apartment',
    palette: 'warm',
    desc: 'Deniz manzaralı, geniş cepheli bir daire. Salondan çıkılan derin balkon Moda Burnu’na bakıyor; mutfak Amerikan, banyolar yenilenmiş. Yapı denetim onaylı 2020 yapı; doğalgazlı kombi, ısı yalıtımı tam.',
    aiNote: 'Bölge ortalamasının %4,2 altında — kısa süreli satılma olasılığı yüksek.',
    aiValue: 9100000,
    aiTrend: '+8,3% yıllık',
    agent: { name: 'Zeynep Aydın', title: 'Senior Danışman, Connective', initials: 'ZA', rating: 4.9 },
    metro: 5,
    features: ['Asansör', 'Otopark', 'Balkon', 'Güvenlik 24/7', 'Site içi'],
  },
  {
    id: 'l2',
    kind: 'satilik',
    title: 'Ataşehir yeni proje 3+1',
    district: 'Ataşehir', city: 'Ataşehir · İstanbul',
    price: 6200000,
    rooms: '3+1', area: 162, floor: '8', age: 0,
    aidat: 1450, heat: 'Merkezi',
    scene: 'tower', palette: 'cool',
    desc: 'Yeni teslim edilen, çelik kapısı ilk açılmış bir daire. 14 katlı projede 8. katta; iki cephesi geniş, salonu çift parçalı.',
    aiValue: 6450000, aiTrend: '+11,0% yıllık',
    agent: { name: 'Mert Demir', title: 'Danışman, Connective', initials: 'MD', rating: 4.7 },
    metro: 8,
    features: ['Asansör', 'Kapalı Otopark', 'Spor Salonu', 'Havuz', 'Güvenlik'],
  },
  {
    id: 'l3',
    kind: 'kiralik',
    title: 'Cihangir’de yenilenmiş 2+1',
    district: 'Cihangir', city: 'Beyoğlu · İstanbul',
    price: 38000,
    rooms: '2+1', area: 92, floor: '3', age: 24,
    aidat: 850, deposit: 2,
    scene: 'historic', palette: 'morn',
    desc: 'Yüksek tavanlı, ahşap zeminli klasik bir Cihangir dairesi. Salon iki cumbalı; mutfak ayrı, banyo komple yenilendi.',
    aiValue: null, aiTrend: '+5,1% yıllık',
    agent: { name: 'Elif Tezcan', title: 'Danışman, Connective', initials: 'ET', rating: 4.8 },
    metro: 3,
    daysAvg: 9,
    features: ['Eşyalı', 'Doğalgaz', 'Kombi', 'Klima', 'Ahşap zemin'],
  },
  {
    id: 'l4',
    kind: 'satilik',
    title: 'Çeşme’de havuzlu müstakil villa',
    district: 'Alaçatı', city: 'Çeşme · İzmir',
    price: 18500000,
    rooms: '5+2', area: 380, floor: '—', age: 4,
    aidat: 0, heat: 'Klima + Şömine',
    scene: 'coast', palette: 'sea',
    desc: '850 m² bahçe içinde, taş cephe villa. Özel havuz, üç tarafı bahçe; deniz iki dakika.',
    aiValue: 19200000, aiTrend: '+14,8% yıllık',
    agent: { name: 'Cem Yıldız', title: 'Lüks Konut Uzmanı', initials: 'CY', rating: 5.0 },
    metro: null,
    features: ['Özel Havuz', 'Bahçe', 'Şömine', 'Tam Eşyalı', 'Garaj'],
  },
  {
    id: 'l5',
    kind: 'kiralik',
    title: 'Levent ofis katı — hazır teslim',
    district: 'Levent', city: 'Beşiktaş · İstanbul',
    price: 145000,
    rooms: 'Ofis', area: 320, floor: '12', age: 3,
    aidat: 4800, deposit: 3,
    scene: 'office', palette: 'cool',
    desc: 'Açık ofis kurgusu, 3 toplantı odası, 2 cam ofis. Klima tam, fiber internet hazır. Anahtar teslim ofise gidebilirsiniz.',
    aiValue: null, aiTrend: '+9,4% yıllık',
    agent: { name: 'Burak Şahin', title: 'Ticari Gayrimenkul', initials: 'BŞ', rating: 4.9 },
    metro: 4,
    daysAvg: 14,
    features: ['Plug & Play', 'Toplantı Odası ×3', 'Fiber', '7/24 Güvenlik'],
  },
  {
    id: 'l6',
    kind: 'satilik',
    title: 'Kadıköy yeni bina 2+1',
    district: 'Caferağa', city: 'Kadıköy · İstanbul',
    price: 4200000,
    rooms: '2+1', area: 110, floor: '3', age: 1,
    aidat: 950, heat: 'Doğalgaz',
    scene: 'apartment', palette: 'morn',
    desc: 'Kadıköy meydanına yürüme mesafesi. Kompakt 2+1, mutfak ayrı, balkon Bağdat Caddesi yönüne bakıyor.',
    aiValue: 4350000, aiTrend: '+7,1% yıllık',
    agent: { name: 'İrem Korkmaz', title: 'Danışman, Connective', initials: 'İK', rating: 4.6 },
    metro: 6,
    features: ['Asansör', 'Otopark', 'Balkon'],
  },
  {
    id: 'l7',
    kind: 'kiralik',
    title: 'Bebek’te boğaz manzaralı 3+1',
    district: 'Bebek', city: 'Beşiktaş · İstanbul',
    price: 92000,
    rooms: '3+1', area: 180, floor: '5', age: 12,
    aidat: 2200, deposit: 2,
    scene: 'historic', palette: 'sea',
    desc: 'Bebek sahiline 3 dakika. Salondan tam boğaz manzarası, mutfak yenilenmiş, ana yatak odası dressing’li.',
    aiValue: null, aiTrend: '+6,8% yıllık',
    agent: { name: 'Defne Erkan', title: 'Senior Danışman', initials: 'DE', rating: 4.9 },
    metro: null,
    daysAvg: 7,
    features: ['Manzara', 'Otopark', '3 Banyo', 'Eşyalı opsiyon'],
  },
  {
    id: 'l8',
    kind: 'satilik',
    title: 'Beyoğlu cumbalı tarihi apartman',
    district: 'Galata', city: 'Beyoğlu · İstanbul',
    price: 5800000,
    rooms: '2+1', area: 130, floor: '2', age: 95,
    aidat: 600, heat: 'Doğalgaz',
    scene: 'historic', palette: 'warm',
    desc: 'Galata Kulesi’ne 4 dakika. Cumbalı, parke zeminli, beş metre tavan; restorasyon görmüş Levanten apartmanında.',
    aiValue: 6050000, aiTrend: '+10,2% yıllık',
    agent: { name: 'Hakan Bilgin', title: 'Kentsel Miras Uzmanı', initials: 'HB', rating: 4.8 },
    metro: 2,
    features: ['Tarihi yapı', 'Cumba', 'Doğalgaz', 'Restorasyonlu'],
  },
  {
    id: 'l9',
    kind: 'kiralik',
    title: 'Bodrum Yalıkavak deniz manzaralı ev',
    district: 'Yalıkavak', city: 'Bodrum · Muğla',
    price: 58000,
    rooms: '3+1', area: 165, floor: '—', age: 8,
    aidat: 1800, deposit: 2,
    scene: 'coast', palette: 'warm',
    desc: 'Marina’ya 5 dakika, taş cephe villa. Geniş veranda, ortak havuz; sezonluk veya yıllık.',
    aiValue: null, aiTrend: '+12,4% yıllık',
    agent: { name: 'Selin Acar', title: 'Lüks Konut Uzmanı', initials: 'SA', rating: 5.0 },
    metro: null,
    daysAvg: 11,
    features: ['Ortak Havuz', 'Veranda', 'Garaj', 'Site içi'],
  },
];

window.LISTINGS = LISTINGS;
window.STEPS = STEPS;
window.fmtTRY = fmtTRY;
